/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorAutor;
import controlador.ControladorConsultas;
import controlador.ControladorLibros;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author laptop
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuMenu = new javax.swing.JMenu();
        mnuAutor = new javax.swing.JMenuItem();
        mnuLibro = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mnuConsultasm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N
        mnuMenu.setMnemonic('f');
        mnuMenu.setText("Menu");

        mnuAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/autor.png"))); // NOI18N
        mnuAutor.setMnemonic('o');
        mnuAutor.setText("Autores");
        mnuAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAutorActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuAutor);

        mnuLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libros.png"))); // NOI18N
        mnuLibro.setMnemonic('s');
        mnuLibro.setText("Libros");
        mnuLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLibroActionPerformed(evt);
            }
        });
        mnuMenu.add(mnuLibro);

        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mnuMenu.add(exitMenuItem);

        menuBar.add(mnuMenu);

        mnuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas.png"))); // NOI18N
        mnuConsultas.setMnemonic('e');
        mnuConsultas.setText("Consultas");

        mnuConsultasm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultas2.png"))); // NOI18N
        mnuConsultasm.setMnemonic('t');
        mnuConsultasm.setText("Consulte Libros y autores");
        mnuConsultasm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultasmActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuConsultasm);

        menuBar.add(mnuConsultas);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAutorActionPerformed
        // TODO add your handling code here:
        AutorF autor = new AutorF();
        ControladorAutor controladorAutor = new ControladorAutor(autor);
        centrarVentana(autor);
        
    }//GEN-LAST:event_mnuAutorActionPerformed

    private void mnuLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibroActionPerformed
        // TODO add your handling code here:
        LibroF libroF = new LibroF();
        ControladorLibros controladorLibros = new ControladorLibros(libroF);
        centrarVentana(libroF);
    }//GEN-LAST:event_mnuLibroActionPerformed

    private void mnuConsultasmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultasmActionPerformed
        // TODO add your handling code here:
        ConsultasF consultasF = new ConsultasF();
        ControladorConsultas controladorConsultas = new ControladorConsultas(consultasF);
        centrarVentana(consultasF);
    }//GEN-LAST:event_mnuConsultasmActionPerformed

    public void centrarVentana(JInternalFrame frame){
        desktopPane.add(frame);
        Dimension dimPrincipalF = desktopPane.getSize();
        Dimension dimVentaF = frame.getSize();
        frame.setLocation((dimPrincipalF.width - dimVentaF.width)/2, (dimPrincipalF.height-dimVentaF.height)/2);
        frame.show();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    public javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenuBar menuBar;
    public javax.swing.JMenuItem mnuAutor;
    public javax.swing.JMenu mnuConsultas;
    public javax.swing.JMenuItem mnuConsultasm;
    public javax.swing.JMenuItem mnuLibro;
    public javax.swing.JMenu mnuMenu;
    // End of variables declaration//GEN-END:variables

}
